config/routes.rb
Rails.application.routes.draw do
  resources :concerts
  resources :musicians
end

app/models/concert.rb
class Concert < ActiveRecord::Base
	has_many :recordings, dependent: :destroy
	has_many :musicians, :through => :recordings
	accepts_nested_attributes_for :musicians, reject_if: :all_blank, allow_destroy: true
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
	belongs_to :musician
	validates :name, uniqueness: true
end

app/models/musician.rb
class Musician < ActiveRecord::Base
	has_many :instruments
	has_many :recordings, dependent: :destroy
	has_many :concerts, :through => :recordings
end

app/models/recording.rb
class Recording < ActiveRecord::Base
  belongs_to :musician
  belongs_to :concert
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
    @musicians = Musician.all
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:place, :data, :musician_ids, :musicians_attributes => [:id, :name, :bio, :_destroy])
    end
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/views/concerts/_concert.html.erb
<%= concert.place %><br />
<%= concert.data %><br />
<% concert.musicians.each do |musician| %>
<%= link_to musician.name, musician_path(musician) %><br />
<% end %>

app/views/concerts/_form.html.erb
<%= form_for(@concert) do |f| %>
  <% if @concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% @concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :place %> <br />
    <%= f.text_field :place %><br /><br />

    <%= f.label :data %><br />
    <%= f.date_field :data %><br /><br />

    <%= f.collection_select(:musician_ids, Musician.all, :id, :name) %> <br />

    <%= f.fields_for :musicians do |musician| %>
      <%= render 'musician_fields', f: musician %>
    <% end %>
    <%= link_to_add_association 'add musician', f, :musicians %><br /><br />

    <%= f.submit %>
  </div>
<% end %>

app/views/concerts/_musician_fields.html.erb
<%= f.label :name %>
<%= f.text_field :name %><br />
<%= f.label :bio %>
<%= f.text_area :bio %><br /><br />
<%= link_to_remove_association "remove musician", f %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form' %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Concerts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.place %>
        <td><%= link_to 'Show', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form' %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>
<%= render @concert %>
<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Through</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>